-- AlterTable
ALTER TABLE `Reg_team` ADD COLUMN `code0` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `code1` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `code2` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `code3` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `code4` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `code5` VARCHAR(191) NOT NULL DEFAULT '';
